version: '3.7'

services:
  origin:
    build: .
    container_name: satta_admin
    ports:
    - "3030:3030/tcp"
    labels:
    - traefik.enable=true
    - "traefik.http.routers.<unique_router_name>.rule=Host(`coolify.io`) && PathPrefix(`/`)"
    - traefik.http.routers.<unique_router_name>.entryPoints=http
    # environment:
    # networks:
    #  myipvlan:
    #    ipv4_address: 192.168.0.12

# networks:
 #  myipvlan:
   #  external: true
   #  name: br0
